# Generated by Django 5.2.6 on 2025-10-02 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=120)),
                ('fayda_number', models.CharField(max_length=120)),
                ('national_id_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_type', models.CharField(choices=[('wadia', 'Wadia Account'), ('mudarabah', 'Mudarabah Account'), ('qard', 'Qard'), ('haji_saving', 'Haji Saving Account'), ('foreign_currency', 'Foreign Currency Account')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_account_applications', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='bank_account.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_branch_manager', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='bank_account.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
