# Generated by Django 5.2.6 on 2025-10-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('age', models.PositiveIntegerField()),
                ('residence', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('position_applied', models.CharField(max_length=255)),
                ('location_applied', models.CharField(max_length=255)),
                ('file_attachment', models.FileField(upload_to='uploads/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('additional_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_employment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('current_employer', models.CharField(blank=True, max_length=255, null=True)),
                ('current_role', models.CharField(blank=True, max_length=255, null=True)),
                ('current_basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('education_details', models.JSONField(blank=True, null=True)),
                ('previous_employers', models.JSONField(blank=True, null=True)),
                ('roles_previous_employers', models.JSONField(blank=True, null=True)),
                ('length_service_previous', models.JSONField(blank=True, null=True)),
                ('total_banking_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('total_non_banking_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
