# Generated by Django 5.2.7 on 2025-10-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='department',
            new_name='category',
        ),
    ]
